### ISSUE TITLE
楼主的roberta哪里下载的呢

### ISSUE THREAD

**Issue by weichen12345** [taojingcong/ccks2021FEE#1]

**Comment by taojingcong** [comment]
在hugging face上下载的，谷歌搜一下或者知乎搜一下如何下载预训练模型就好

--------------原始邮件--------------
发件人："weichen12345 ***@***.***&gt;;
发送时间：2021年7月29日(星期四) 下午2:37
收件人："taojingcong/ccks2021FEE" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[taojingcong/ccks2021FEE] 楼主的roberta哪里下载的呢 (#1)
-----------------------------------

**Comment by weichen12345** [comment]
好的，谢谢了！
