### ISSUE TITLE
event dection部分的loss

### ISSUE THREAD

**Issue by jdcmj** [taojingcong/ccks2021FEE#2]
请问event dection部分的loss里为什么要设置有simBCE这个loss呢

**Comment by taojingcong** [comment]
这个写错了，应该是simcse，来自一篇对比学习的论文，可以搜下知乎。不过在本实验中这东西没啥用，去掉也行

--------------原始邮件--------------
发件人："jdcmj ***@***.***&gt;;
发送时间：2021年7月29日(星期四) 晚上7:53
收件人："taojingcong/ccks2021FEE" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[taojingcong/ccks2021FEE] event dection部分的loss (#2)
-----------------------------------

 

 
请问event dection部分的loss里为什么要设置有simBCE这个loss呢
